### PR TITLE
171 short year detected

### LINKED ISSUE #171: Short year detected
In bill inHQfeSqLniJys2dk.PDF the year `203` is detected.

### PR DESCRIPTION
**Pull request by tamacodechi**
Closes #171 
The issue is actually an OCR issue. But this fixes the fact that an incorrect date gets detected that should not.

**Actual data:**
screen shot 2017-02-03 at 10 23 07

**What gets read:**
screen shot 2017-02-03 at 10 21 46

### CODE REVIEW

**Comment by clemenshelm** [comment]
Why doesn't this close the issue? The issue already states that 203 is detected …

**Comment by tamacodechi** [comment]
Ahh okay, well it doesn't make it so the correct date is detected only that the incorrect date is **not** detected 😅

**Comment by clemenshelm** [comment]
That's a reasonable fix, though 😄

**Comment by clemenshelm** [comment]
Even if it's not correct, at least it's less wrong 😉

**Comment by clemenshelm** [comment]
Can you associate it with the issue and can I merge it then?

**Review by clemenshelm — APPROVED** [review]

**Comment by tamacodechi** [comment]
True, to me it was more: the actual problem is that 2016 gets detected as 203 6, but this stops _another_ problem which is that 203 gets detected as a date, so it doesn't fix **this** issues, but it certainly fixes an issue the recognizer had 😁  So I didn't feel this qualified as closing the issue but rather fix a by product of the actual issue, where we should still need to fix that OCR issue along the way.

Awesome, will do 🎉 

 >The slightly obsessive person in me is now glad that we have data making us get rid of all those nasty ```d+``` regexes. Can't wait 'til they all need ```20\d{2}``` kind of limitation 😆

**Pull request merged**
